1357 custom request agent
bcgov/CONN-CCBC-portal pull request #1414
Opened 2023-03-30 18:31 UTC by marcellmueller

- feat: add aws custom http and https agents
- feat: capture errors with sentry in custom http handlers

Implements # \<issue number\>

2023-04-03 17:22 UTC, AntBush requested changes

2023-04-03 17:22 UTC, AntBush commented on app/backend/lib/awsCommon.ts
>    httpOptions: {
I think the httpOptions are deprecated on v3 of the client, if anything adding the type of `S3ClientConfig` to the object can help with that. `retryDelayOptions` is also not available along with maxRetries (I think was renamed to maxAttempts)

2023-04-03 17:22 UTC, AntBush commented on app/backend/lib/awsCommon.ts
> +  httpsAgent,
Here we can set the connectionTimeout to 30 seconds rather than the awsConfig object

2023-04-03 19:11 UTC, marcellmueller commented on app/backend/lib/CustomHttpsAgent.ts
> +        `Currently trying to connect to: ${address} for host: ${host}`
So we don't need the lookup section at all? This context would have saved me a lot of time testing this ticket.

2023-04-03 20:57 UTC, AntBush commented on app/backend/lib/CustomHttpsAgent.ts
> +        `Currently trying to connect to: ${address} for host: ${host}`
Oh no we do need the lookup section to save the address, but not the `console.log` here

2023-04-04 22:37 UTC, AntBush approved these changes

2023-04-04 23:09 UTC, merged