Dashboard fixes testing
bcgov/CONN-CCBC-portal pull request #389
Opened 2022-08-09 22:33 UTC by marcellmueller

This PR adds Relay testing helpers from cif and unit tests for the dashboard. It also fixes to the dashboard withdraw button z-index and also minor fixes to the edit/view button and url handling.

2022-08-10 15:37 UTC, wenzowski requested changes
One small opportunity for reafactor but still missing pgtap validation of api permissions.

2022-08-10 15:37 UTC, wenzowski commented on app/components/Dashboard/Table.tsx
> +              }
We've got this logic duplicated a bit. Can we consider an `isEditable()` helper to refactor out the duplicated chained elif?

2022-08-10 15:37 UTC, wenzowski commented on app/tests/components/Dashboard/Dashboard.test.tsx
> +});
these are all valuable test cases; what's missing now is db unit tests to confirm the expected permissions for mutability and access are respected. These tests confirm that the user can see whether something should be editable or view only but not whether those applications are actually edit-protected or view-protected. The additional tests should be done at pgtap level.

2022-08-15 22:20 UTC, VB-at-Bis approved these changes
Looks good

2022-08-15 22:26 UTC, merged