fix: set cookie time
bcgov/CONN-CCBC-portal pull request #681
Opened 2022-09-21 19:36 UTC by AntBush

Branch to have consistent happo screens

2022-09-21 21:14 UTC, matthieu-foucault commented
@AntBush to ensure screenshot consistency, you'll want to wait until the mutations complete. Asserting that `Last saved` is displayed in the status component before calling happo should do it.

2022-09-21 21:25 UTC, AntBush commented
> Asserting that `Last saved` is displayed in the status component before calling happo should do it.

True, I checked the happo diffs as well and the cookie set that I did wasn't recognized/sent along. The happo diffs show that it isn't being set to Oct 10 2022.  @matthieu-foucault Any thoughts on this? I don't see anything immediate that is wrong here especially since

2022-09-21 21:27 UTC, matthieu-foucault commented
Are we 
- deploying the `mocks` schema before running our end-to-end tests?
- running our server with the correct env variables?

2022-09-27 15:10 UTC, matthieu-foucault requested changes

2022-09-27 15:26 UTC, AntBush commented on app/cypress/integration/index.spec.js
>      cy.get('body').happoScreenshot();
Added some names

2022-09-27 15:27 UTC, AntBush commented on app/cypress/integration/index.spec.js
> +    cy.setCookie('mocks.mocked_date', mockedDateString);
Added the useMockedDate function and the clearMockedDate function

2022-09-27 16:13 UTC, matthieu-foucault commented on app/components/Form/ApplicationFormStatus.tsx
> +const SavingStatusContainer = styled('header')`
Sorry, I meant that the flexbox in `ApplicationForm` should be the one turned into a header, not this one, since it contains the `h1` element.

2022-09-27 16:14 UTC, matthieu-foucault commented on app/components/Form/ApplicationFormStatus.tsx
> +      <SavingStatusContainer aria-live="off" aria-label="status container">
```suggestion
      <SavingStatusContainer aria-live="off" aria-label="form saving status">
```

This label would be read by a screen reader, so it should make sense to our user

2022-09-27 16:57 UTC, matthieu-foucault approved these changes
:shipit:

2022-09-27 17:15 UTC, merged