feat: updates and comments to team agreement
bcgov/CONN-CCBC-portal pull request #686
Opened 2022-09-22 00:25 UTC by VB-at-Bis

### Description

Updated Team Agreement and discussion points (marked as [TBD]- to Be Discussed)

2022-09-22 14:55 UTC, matthieu-foucault commented on docs/Team_Agreements.md
> +### Grooming cards
```suggestion
### Refining cards
```
Due to some connotations of the word "grooming", "backlog refinement" is now preferred

2022-09-22 17:50 UTC, AntBush requested changes
Some spelling errors. Additionally, I think some things like scheduling time for refinement in-sprint and a new planning-poker/estimation tool are part of the refined agreements. 

The bug likelihood/impact matrix is something we also want to implement (but idk if that goes here or somewhere else)

2022-09-26 15:27 UTC, VB-at-Bis commented on docs/Team_Agreements.md
> +- Card should pass Definition of Ready (DoR) before it can be moved as a strint candidate
fixed

2022-10-12 22:22 UTC, matthieu-foucault approved these changes
I renamed the file to `CONTRIBUTING.md`, following the github convention, which should make the contributing guidelines easily visible when creating issues/PRs

2022-10-17 16:17 UTC, AntBush approved these changes
LGTM

2022-10-17 18:17 UTC, merged