test: server and cypress support mock logins with different roles
bcgov/CONN-CCBC-portal pull request #837
Opened 2022-10-27 23:38 UTC by matthieu-foucault

Required for e2e tests in #32 and #639

2022-10-28 13:56 UTC, marcellmueller approved these changes
Thanks for doing this, looks great. 

Do you think a small section in the readme explaining how this works would be helpful?

2022-10-28 14:00 UTC, marcellmueller requested changes
Oh it looks like the test is failing CI

2022-11-01 17:45 UTC, marcellmueller commented on docs/auth.md
> +# Authentication and Authorization
Thanks for this :heart:

2022-11-01 17:51 UTC, marcellmueller approved these changes
Nice job and I appreciate the readme and eliminating a lot of the `cy.wait` throughout the tests.

I noticed a few in some tests still such as `upload.spec.js`, I assume those are still needed? `cy.contains` doesn't help in every scenario?

2022-11-01 17:51 UTC, merged

2022-11-01 18:09 UTC, matthieu-foucault commented
> I noticed a few in some tests still such as upload.spec.js, I assume those are still needed? cy.contains doesn't help in every scenario?

They may not be needed anymore. I did a search and replace of the `cy.get().contains(` pattern, so I didn't look into the `upload.spec.js` too much

Some `wait`s on the initial page load are still needed, as we have "detached DOM" issues otherwise, caused by the may renders that occur on page load